### ISSUE TITLE
Pre-build checks - Lessons from v1.8.4

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/releases#12]
1. check following files are executable in ~/NanoHatOLED/BakeBit/Software/Python/scripts:
-  bettercap_ctl
- kismet_ctl
- profiler_ctl
2. Check /etc/sudoers.d/wlanpidump looks like this:
- wlanpi ALL = (root) NOPASSWD: /sbin/iwconfig, /usr/sbin/iw, /bin/date

**Comment by jiribrejcha** [comment]
Will keep those in mind 👍🏻
