### ISSUE TITLE
"port blinker" feature

### ISSUE THREAD

**Issue by garci66** [WLAN-Pi/releases#18]
It would be great if we could add a "port blinker"  feature to the system. In this way, the ethernet port's "phy" is enabled/disabled every x seconds (3 seconds up, 3 seconds down for example). In this way, one can plug the wlan-pi to a remote port, set the port-blinker feature on and then look at the switch -either in CLI, log or directly at the port LEDs and see which one is blinking. Thus finding your port.

This would be like a virtual "cable beeper" / "cable locator".

**Comment by jiribrejcha** [comment]
Great suggestion, thanks. Keep them coming.

**Comment by jiribrejcha** [comment]
Diego, thanks again for the suggestion. Blinker will be included in the upcoming 2.0 release.

**Comment by garci66** [comment]
great!! Off topic, but let me know if you need help with the LLDP ticket #19 ... . We can discuss it on that ticket.. but be glad to help

**Comment by jiribrejcha** [comment]
Released in 2.0.0. Thanks for the suggestion, Diego.
